from __future__ import annotations

STATUS_ANALYSIS_READY = "analysis_ready"
STATUS_REVIEW_CONFIRM = "review_confirm"
STATUS_REVIEW_CORRECT = "review_correct"
STATUS_REVIEW_PREFIX = "review_"
STATUS_WRITEBACK_SENT = "writeback_sent"

WRITEBACK_ALLOWED_STATUSES = {STATUS_REVIEW_CONFIRM, STATUS_REVIEW_CORRECT}
WORKLIST_ACTIVE_EXCLUDED_STATUSES = {
    f"{STATUS_REVIEW_PREFIX}question",
    f"{STATUS_REVIEW_PREFIX}reject",
    STATUS_WRITEBACK_SENT,
}

PIPELINE_STAGE_INBOX = "inbox"
PIPELINE_STAGE_PYPDF = "pypdf"
PIPELINE_STAGE_OCR = "ocr"
PIPELINE_STAGE_MODEL = "model"
PIPELINE_STAGE_VALIDATION = "validation"
PIPELINE_STAGE_WORKLIST = "worklist"
PIPELINE_STAGE_REVIEW = "review"
PIPELINE_STAGE_OUTPUT = "output"
PIPELINE_STAGE_WRITEBACK = "writeback"
PIPELINE_STAGE_ERROR = "error"

PIPELINE_STAGES = {
    PIPELINE_STAGE_INBOX,
    PIPELINE_STAGE_PYPDF,
    PIPELINE_STAGE_OCR,
    PIPELINE_STAGE_MODEL,
    PIPELINE_STAGE_VALIDATION,
    PIPELINE_STAGE_WORKLIST,
    PIPELINE_STAGE_REVIEW,
    PIPELINE_STAGE_OUTPUT,
    PIPELINE_STAGE_WRITEBACK,
    PIPELINE_STAGE_ERROR,
}

PIPELINE_STATUS_STARTED = "started"
PIPELINE_STATUS_OK = "ok"
PIPELINE_STATUS_WARNING = "warning"
PIPELINE_STATUS_FAILED = "failed"
PIPELINE_STATUS_COMPLETED = "completed"

PIPELINE_STATUSES = {
    PIPELINE_STATUS_STARTED,
    PIPELINE_STATUS_OK,
    PIPELINE_STATUS_WARNING,
    PIPELINE_STATUS_FAILED,
    PIPELINE_STATUS_COMPLETED,
}

PIPELINE_UI_STATUS_PENDING = "pending"
PIPELINE_UI_STATUS_UNKNOWN = "unknown"

REVIEW_DECISION_LABELS = {
    "confirm": "Freigeben",
    "correct": "Korrigieren & Freigeben",
    "question": "Rueckfrage stellen",
    "reject": "Ablehnen",
}

REVIEW_DECISION_OUTPUT_FOLDERS = {
    "confirm": "confirmed",
    "correct": "corrected",
    "question": "questions",
    "reject": "rejected",
}
